preset: laravel

enabled:
- length_ordered_imports
- long_list_syntax
- phpdoc_add_missing_param_annotation

disabled:
- short_list_syntax
- alpha_ordered_imports
- single_class_element_per_statement
